server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8

spring:
  redis:
    host: localhost
    port: 6379
    database: 2
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
  transaction:
    rollback-on-commit-failure: true
  banner:
    location: banner.txt
  application:
    name: shortlink
  datasource:
    url: jdbc:mysql://localhost:3306/shortlink?characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  http:
    encoding:
      charset: UTF-8
      enabled: true

service:
  domain: http://localhost:${server.port}/

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /actuator
  endpoint:
    beans:
      enabled: true
    shutdown:
      enabled: true

logging:
  level:
    root: info
  path: logs
  file:
      max-size: 15MB
  pattern:
      dateformat: yyyy-MM-dd HH:mm:ss.SSS


